Movie.find_or_create_by!(title:"TRON: Legacy", poster_img_url:"https://image.tmdb.org/t/p/w500/vuifSABRpSnxCAOxEnWpNbZSXpp.jpg", imdb_page:"https://www.imdb.com/title/tt1104001/")
Movie.find_or_create_by!(title:"Limitless", poster_img_url:"https://image.tmdb.org/t/p/w500/hv5JMCrMVLvV6HKPf9FcBuyk2MG.jpg", imdb_page:"https://www.imdb.com/title/tt1219289/")
Movie.find_or_create_by!(title:"The Fifth Element", poster_img_url:"https://image.tmdb.org/t/p/w500/fPtlCO1yQtnoLHOwKtWz7db6RGU.jpg", imdb_page:"https://www.imdb.com/title/tt0119116/")
Movie.find_or_create_by!(title:"Groundhog Day", poster_img_url:"https://image.tmdb.org/t/p/w500/wIUz1J3RBBu88NAwTqLdHu4sGOP.jpg", imdb_page:"https://www.imdb.com/title/tt0107048/")
Movie.find_or_create_by!(title:"Training Day", poster_img_url:"https://image.tmdb.org/t/p/w500/bUeiwBQdupBLQthMCHKV7zv56uv.jpg", imdb_page:"https://www.imdb.com/title/tt0139654/")
Movie.find_or_create_by!(title:"They Live", poster_img_url:"https://image.tmdb.org/t/p/w500/ngnybFTuopfbfmmEeX9jjBQQmF6.jpg", imdb_page:"https://www.imdb.com/title/tt0096256/")
Movie.find_or_create_by!(title:"The Five People You Meet in Heaven", poster_img_url:"https://image.tmdb.org/t/p/w500/1fvMz3gy4YuqPDC5LotTWofFFcx.jpg", imdb_page:"https://www.imdb.com/title/tt0400435/")
Movie.find_or_create_by!(title:"Demolition Man", poster_img_url:"https://image.tmdb.org/t/p/w500/dq6AmlVFo92PRuoLCcIyFdoRuxf.jpg", imdb_page:"https://www.imdb.com/title/tt0106697/")
Movie.find_or_create_by!(title:"Lucy", poster_img_url:"https://image.tmdb.org/t/p/w500/dhjyfcwEoW6jJ4Q7DpZTp6E58GA.jpg", imdb_page:"https://www.imdb.com/title/tt2872732/")
Movie.find_or_create_by!(title:"I Origins", poster_img_url:"https://image.tmdb.org/t/p/w500/2P31jhd1dWUAPD8dmnSrwkQ8CNN.jpg", imdb_page:"https://www.imdb.com/title/tt2884206/")
Movie.find_or_create_by!(title:"In Time", poster_img_url:"https://image.tmdb.org/t/p/w500/3Mwj2sIONQckOZP3YwsUXF7U5I4.jpg", imdb_page:"https://www.imdb.com/title/tt1637688/")
Movie.find_or_create_by!(title:"Iron Man", poster_img_url:"https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg", imdb_page:"https://www.imdb.com/title/tt0371746/")
Movie.find_or_create_by!(title:"Mad Max", poster_img_url:"https://image.tmdb.org/t/p/w500/5LrI4GiCSrChgkdskVZiwv643Kg.jpg", imdb_page:"https://www.imdb.com/title/tt0079501/")
Movie.find_or_create_by!(title:"Hummingbird", poster_img_url:"https://image.tmdb.org/t/p/w500/bN2aGUOxHRwGms68WTDr2MHzkKa.jpg", imdb_page:"https://www.imdb.com/title/tt1893256/")
Movie.find_or_create_by!(title:"Mr. Nobody", poster_img_url:"https://image.tmdb.org/t/p/w500/qNkIONc4Rgmzo23ph7qWp9QfVnW.jpg", imdb_page:"https://www.imdb.com/title/tt0485947/")
Movie.find_or_create_by!(title:"The Great Gatsby", poster_img_url:"https://image.tmdb.org/t/p/w500/nimh1rrDDLhgpG8XAYoUZXHYwb6.jpg", imdb_page:"https://www.imdb.com/title/tt1343092/")
Movie.find_or_create_by!(title:"Revolver", poster_img_url:"https://image.tmdb.org/t/p/w500/cXJYFEIGNxiNTCekP1A68ICzJen.jpg", imdb_page:"https://www.imdb.com/title/tt0365686/")
Movie.find_or_create_by!(title:"Ponyo", poster_img_url:"https://image.tmdb.org/t/p/w500/yp8vEZflGynlEylxEesbYasc06i.jpg", imdb_page:"https://www.imdb.com/title/tt0876563/")
Movie.find_or_create_by!(title:"Unbreakable", poster_img_url:"https://image.tmdb.org/t/p/w500/mLuehrGLiK5zFCyRmDDOH6gbfPf.jpg", imdb_page:"https://www.imdb.com/title/tt0217869/")
Movie.find_or_create_by!(title:"Goodfellas", poster_img_url:"https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg", imdb_page:"https://www.imdb.com/title/tt0099685/")
Movie.find_or_create_by!(title:"Boyz N The Hood", poster_img_url:"https://image.tmdb.org/t/p/w500/v4ox4aSCNT5vyLXl4Q71JiWwCXW.jpg", imdb_page:"https://www.imdb.com/title/tt0101507/")
Movie.find_or_create_by!(title:"Beetlejuice", poster_img_url:"https://image.tmdb.org/t/p/w500/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg", imdb_page:"https://www.imdb.com/title/tt0094721/")
Movie.find_or_create_by!(title:"The Holy Mountain", poster_img_url:"https://image.tmdb.org/t/p/w500/cZemtR2mXzqu4zLSMEzLbOQYMQp.jpg", imdb_page:"https://www.imdb.com/title/tt0071615/")
Movie.find_or_create_by!(title:"They Cloned Tyrone", poster_img_url:"https://image.tmdb.org/t/p/w500/omSa3oafsV7i5776FLFoOBI2Ho9.jpg", imdb_page:"https://www.imdb.com/title/tt9873892/")
Movie.find_or_create_by!(title:"Wanted", poster_img_url:"https://image.tmdb.org/t/p/w500/cbDMsV4VJAL2xJ2JXdWWjmUXZkT.jpg", imdb_page:"https://www.imdb.com/title/tt0493464/")
Movie.find_or_create_by!(title:"Rango", poster_img_url:"https://image.tmdb.org/t/p/w500/oVeRl1SRADz74OrY97usmP1flLV.jpg", imdb_page:"https://www.imdb.com/title/tt1192628/")
Movie.find_or_create_by!(title:"Soul", poster_img_url:"https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg", imdb_page:"https://www.imdb.com/title/tt2948372/")
Movie.find_or_create_by!(title:"Cars", poster_img_url:"https://image.tmdb.org/t/p/w500/abW5AzHDaIK1n9C36VdAeOwORRA.jpg", imdb_page:"https://www.imdb.com/title/tt0317219/")
Movie.find_or_create_by!(title:"The Wolf of Wall Street", poster_img_url:"https://image.tmdb.org/t/p/w500/34m2tygAYBGqA9MXKhRDtzYd4MR.jpg", imdb_page:"https://www.imdb.com/title/tt0993846/")
Movie.find_or_create_by!(title:"Life of Pi", poster_img_url:"https://image.tmdb.org/t/p/w500/iLgRu4hhSr6V1uManX6ukDriiSc.jpg", imdb_page:"https://www.imdb.com/title/tt0454876/")
Movie.find_or_create_by!(title:"Everything Everywhere All at Once", poster_img_url:"https://image.tmdb.org/t/p/w500/w3LxiVYdWWRvEVdn5RYq6jIqkb1.jpg", imdb_page:"https://www.imdb.com/title/tt6710474/")
Movie.find_or_create_by!(title:"Transformers: Dark of the Moon", poster_img_url:"https://image.tmdb.org/t/p/w500/28YlCLrFhONteYSs9hKjD1Km0Cj.jpg", imdb_page:"https://www.imdb.com/title/tt1399103/")
Movie.find_or_create_by!(title:"The Matrix", poster_img_url:"https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", imdb_page:"https://www.imdb.com/title/tt0133093/")
Movie.find_or_create_by!(title:"The Silence of the Lambs", poster_img_url:"https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg", imdb_page:"https://www.imdb.com/title/tt0102926/")
Movie.find_or_create_by!(title:"The Dark Knight Rises", poster_img_url:"https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg", imdb_page:"https://www.imdb.com/title/tt1345836/")
Movie.find_or_create_by!(title:"Enter the Void", poster_img_url:"https://image.tmdb.org/t/p/w500/krKnsfvSJM1PL40tLicRhVQ6kuG.jpg", imdb_page:"https://www.imdb.com/title/tt1191111/")
Movie.find_or_create_by!(title:"50/50", poster_img_url:"https://image.tmdb.org/t/p/w500/8f9tM9JVB4ETBhxlQcXIjLckArl.jpg", imdb_page:"https://www.imdb.com/title/tt1306980/")
Movie.find_or_create_by!(title:"About Time", poster_img_url:"https://image.tmdb.org/t/p/w500/iR1bVfURbN7r1C46WHFbwCkVve.jpg", imdb_page:"https://www.imdb.com/title/tt2194499/")
Movie.find_or_create_by!(title:"The Secret Life of Walter Mitty", poster_img_url:"https://image.tmdb.org/t/p/w500/tY6ypjKOOtujhxiSwTmvA4OZ5IE.jpg", imdb_page:"https://www.imdb.com/title/tt0359950/")
Movie.find_or_create_by!(title:"Birdman or (The Unexpected Virtue of Ignorance)", poster_img_url:"https://image.tmdb.org/t/p/w500/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg", imdb_page:"https://www.imdb.com/title/tt2562232/")
Movie.find_or_create_by!(title:"Free Guy", poster_img_url:"https://image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg", imdb_page:"https://www.imdb.com/title/tt6264654/")
Movie.find_or_create_by!(title:"Ready Player One", poster_img_url:"https://image.tmdb.org/t/p/w500/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg", imdb_page:"https://www.imdb.com/title/tt1677720/")
Movie.find_or_create_by!(title:"The Usual Suspects", poster_img_url:"https://image.tmdb.org/t/p/w500/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg", imdb_page:"https://www.imdb.com/title/tt0114814/")
Movie.find_or_create_by!(title:"Peaceful Warrior", poster_img_url:"https://image.tmdb.org/t/p/w500/r4VQCZe3aSo7TmmsxcyLqaoMR1l.jpg", imdb_page:"https://www.imdb.com/title/tt0438315/")
Movie.find_or_create_by!(title:"What Dreams May Come", poster_img_url:"https://image.tmdb.org/t/p/w500/2gUfJKfJ6LwdqQebiAWuNzIWyp9.jpg", imdb_page:"https://www.imdb.com/title/tt0120889/")
Movie.find_or_create_by!(title:"Uncle Buck", poster_img_url:"https://image.tmdb.org/t/p/w500/i0MuRxuENc9Ur3croChw0Tmrs5G.jpg", imdb_page:"https://www.imdb.com/title/tt0098554/")
Movie.find_or_create_by!(title:"The Wizard of Oz", poster_img_url:"https://image.tmdb.org/t/p/w500/bSA6DbAC5gdkaooU164lQUX6rVs.jpg", imdb_page:"https://www.imdb.com/title/tt0032138/")
Movie.find_or_create_by!(title:"American Psycho", poster_img_url:"https://image.tmdb.org/t/p/w500/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg", imdb_page:"https://www.imdb.com/title/tt0144084/")
Movie.find_or_create_by!(title:"Half Baked", poster_img_url:"https://image.tmdb.org/t/p/w500/14TmEac4bquNaEld9t0uIliYoKE.jpg", imdb_page:"https://www.imdb.com/title/tt0120693/")
Movie.find_or_create_by!(title:"Slacker", poster_img_url:"https://image.tmdb.org/t/p/w500/uNtzrTiQQMHwabGr0aAi8TvuII9.jpg", imdb_page:"https://www.imdb.com/title/tt0102943/")
Movie.find_or_create_by!(title:"Waking Life", poster_img_url:"https://image.tmdb.org/t/p/w500/mhqBB8Bvy8q06mmwZQO8rFSzWCs.jpg", imdb_page:"https://www.imdb.com/title/tt0243017/")
Movie.find_or_create_by!(title:"Joker", poster_img_url:"https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", imdb_page:"https://www.imdb.com/title/tt7286456/")
Movie.find_or_create_by!(title:"Into the Wild", poster_img_url:"https://image.tmdb.org/t/p/w500/2MSGZEE6XZd2r4ODNziwAw7Hpw0.jpg", imdb_page:"https://www.imdb.com/title/tt0758758/")
Movie.find_or_create_by!(title:"Akira", poster_img_url:"https://image.tmdb.org/t/p/w500/neZ0ykEsPqxamsX6o5QNUFILQrz.jpg", imdb_page:"https://www.imdb.com/title/tt0094625/")
Movie.find_or_create_by!(title:"Sympathy for the Devil", poster_img_url:"https://image.tmdb.org/t/p/w500/afGdVMa80LMs6ibLP22CwM5uI4e.jpg", imdb_page:"https://www.imdb.com/title/tt21991654/")
Movie.find_or_create_by!(title:"Ghost in the Shell", poster_img_url:"https://image.tmdb.org/t/p/w500/9gC88zYUBARRSThcG93MvW14sqx.jpg", imdb_page:"https://www.imdb.com/title/tt0113568/")
Movie.find_or_create_by!(title:"Source Code", poster_img_url:"https://image.tmdb.org/t/p/w500/faCR2lavXBKeCS6N7STIMDLMCDL.jpg", imdb_page:"https://www.imdb.com/title/tt0945513/")
Movie.find_or_create_by!(title:"Little Buddha", poster_img_url:"https://image.tmdb.org/t/p/w500/xy70xtdoKZ3PxlKkakwdhL3UFDQ.jpg", imdb_page:"https://www.imdb.com/title/tt0107426/")
Movie.find_or_create_by!(title:"Doctor Strange", poster_img_url:"https://image.tmdb.org/t/p/w500/uGBVj3bEbCoZbDjjl9wTxcygko1.jpg", imdb_page:"https://www.imdb.com/title/tt1211837/")
Movie.find_or_create_by!(title:"Deep Cover", poster_img_url:"https://image.tmdb.org/t/p/w500/etr2mCm7gMufAJkSLuB23XocDtd.jpg", imdb_page:"https://www.imdb.com/title/tt0104073/")
Movie.find_or_create_by!(title:"Close Encounters of the Third Kind", poster_img_url:"https://image.tmdb.org/t/p/w500/4zfedS25uMAhgm6YQhc9bhKHbLl.jpg", imdb_page:"https://www.imdb.com/title/tt0075860/")
Movie.find_or_create_by!(title:"Videodrome", poster_img_url:"https://image.tmdb.org/t/p/w500/qqqkiZSU9EBGZ1KiDmfn07S7qvv.jpg", imdb_page:"https://www.imdb.com/title/tt0086541/")
Movie.find_or_create_by!(title:"In Full Bloom", poster_img_url:"https://image.tmdb.org/t/p/w500/613YOhOiOxQMj80Relyq6ip4xsV.jpg", imdb_page:"https://www.imdb.com/title/tt4538670/")
Movie.find_or_create_by!(title:"The Adventures of Tintin", poster_img_url:"https://image.tmdb.org/t/p/w500/mKYkNro2btaWMsnYSuyqrBdHQo3.jpg", imdb_page:"https://www.imdb.com/title/tt0983193/")
Movie.find_or_create_by!(title:"The Sting", poster_img_url:"https://image.tmdb.org/t/p/w500/ckmYng37zey8INYf6d10cVgIG93.jpg", imdb_page:"https://www.imdb.com/title/tt0070735/")
Movie.find_or_create_by!(title:"Avatar", poster_img_url:"https://image.tmdb.org/t/p/w500/kyeqWdyUXW608qlYkRqosgbbJyK.jpg", imdb_page:"https://www.imdb.com/title/tt0499549/")
Movie.find_or_create_by!(title:"The Boys from Brazil", poster_img_url:"https://image.tmdb.org/t/p/w500/w7IZT1HJNmWcEj3Axwlwhya02OX.jpg", imdb_page:"https://www.imdb.com/title/tt0077269/")
Movie.find_or_create_by!(title:"The Illusionist", poster_img_url:"https://image.tmdb.org/t/p/w500/4I1oOPHNrHLcvz3wTMuETJLws9z.jpg", imdb_page:"https://www.imdb.com/title/tt0443543/")
Movie.find_or_create_by!(title:"Fallen Angels", poster_img_url:"https://image.tmdb.org/t/p/w500/yyM9BPdwttK5LKZSLvHae7QPKo1.jpg", imdb_page:"https://www.imdb.com/title/tt0112913/")
Movie.find_or_create_by!(title:"Casino", poster_img_url:"https://image.tmdb.org/t/p/w500/6zEZY1htzRos2w0W3T7o7W1WJhp.jpg", imdb_page:"https://www.imdb.com/title/tt0112641/")
Movie.find_or_create_by!(title:"Donnie Brasco", poster_img_url:"https://image.tmdb.org/t/p/w500/xtKLvpOfARi1XVm8u2FTdhY5Piq.jpg", imdb_page:"https://www.imdb.com/title/tt0119008/")
Movie.find_or_create_by!(title:"Bonnie and Clyde", poster_img_url:"https://image.tmdb.org/t/p/w500/sCSQFK9kMsprT4jgWqgw82dT6WI.jpg", imdb_page:"https://www.imdb.com/title/tt0061418/")
Movie.find_or_create_by!(title:"My Life as a Zucchini", poster_img_url:"https://image.tmdb.org/t/p/w500/2uu8fIzl76C9MFiUQhjKYSLKVq.jpg", imdb_page:"https://www.imdb.com/title/tt2321405/")
Movie.find_or_create_by!(title:"1917", poster_img_url:"https://image.tmdb.org/t/p/w500/iZf0KyrE25z1sage4SYFLCCrMi9.jpg", imdb_page:"https://www.imdb.com/title/tt8579674/")
Movie.find_or_create_by!(title:"Zootopia", poster_img_url:"https://image.tmdb.org/t/p/w500/hlK0e0wAQ3VLuJcsfIYPvb4JVud.jpg", imdb_page:"https://www.imdb.com/title/tt2948356/")
Movie.find_or_create_by!(title:"Gotti", poster_img_url:"https://image.tmdb.org/t/p/w500/9SVKC2ef0aqVbThlEGppRTdAiZu.jpg", imdb_page:"https://www.imdb.com/title/tt0116441/")
Movie.find_or_create_by!(title:"Jackie Brown", poster_img_url:"https://image.tmdb.org/t/p/w500/ewbLUXvm4riZL0aepy90o0vMesn.jpg", imdb_page:"https://www.imdb.com/title/tt0119396/")
Movie.find_or_create_by!(title:"The Man from Earth", poster_img_url:"https://image.tmdb.org/t/p/w500/V086R82gNgWrotaXZFO4JhdgB1.jpg", imdb_page:"https://www.imdb.com/title/tt0756683/")
Movie.find_or_create_by!(title:"The Holdovers", poster_img_url:"https://image.tmdb.org/t/p/w500/VHSzNBTwxV8vh7wylo7O9CLdac.jpg", imdb_page:"https://www.imdb.com/title/tt14849194/")
Movie.find_or_create_by!(title:"Wild Tales", poster_img_url:"https://image.tmdb.org/t/p/w500/bU7IUeTdYFOgeUPtwpWKQNhORMC.jpg", imdb_page:"https://www.imdb.com/title/tt3011894/")
Movie.find_or_create_by!(title:"Mars Express", poster_img_url:"https://image.tmdb.org/t/p/w500/mpGbDJUsPdnoy4Xukz7S4tZRciN.jpg", imdb_page:"https://www.imdb.com/title/tt26915336/")
Movie.find_or_create_by!(title:"Transformers One", poster_img_url:"https://image.tmdb.org/t/p/w500/qrwI2T844nrBUv3eDwQZRDdgSFs.jpg", imdb_page:"https://www.imdb.com/title/tt8864596/")
