Movie.create(title:"TRON: Legacy", poster_img_url:"https://image.tmdb.org/t/p/w500/vuifSABRpSnxCAOxEnWpNbZSXpp.jpg", imdb_page:"https://www.imdb.com/title/tt1104001/")
Movie.create(title:"Limitless", poster_img_url:"https://image.tmdb.org/t/p/w500/hv5JMCrMVLvV6HKPf9FcBuyk2MG.jpg", imdb_page:"https://www.imdb.com/title/tt1219289/")
Movie.create(title:"The Fifth Element", poster_img_url:"https://image.tmdb.org/t/p/w500/fPtlCO1yQtnoLHOwKtWz7db6RGU.jpg", imdb_page:"https://www.imdb.com/title/tt0119116/")
Movie.create(title:"Groundhog Day", poster_img_url:"https://image.tmdb.org/t/p/w500/wIUz1J3RBBu88NAwTqLdHu4sGOP.jpg", imdb_page:"https://www.imdb.com/title/tt0107048/")
Movie.create(title:"Training Day", poster_img_url:"https://image.tmdb.org/t/p/w500/bUeiwBQdupBLQthMCHKV7zv56uv.jpg", imdb_page:"https://www.imdb.com/title/tt0139654/")
Movie.create(title:"They Live", poster_img_url:"https://image.tmdb.org/t/p/w500/ngnybFTuopfbfmmEeX9jjBQQmF6.jpg", imdb_page:"https://www.imdb.com/title/tt0096256/")
Movie.create(title:"The Five People You Meet in Heaven", poster_img_url:"https://image.tmdb.org/t/p/w500/1fvMz3gy4YuqPDC5LotTWofFFcx.jpg", imdb_page:"https://www.imdb.com/title/tt0400435/")
Movie.create(title:"Demolition Man", poster_img_url:"https://image.tmdb.org/t/p/w500/pxWuGsyzVQSqHWxVQLy4XUcopIL.jpg", imdb_page:"https://www.imdb.com/title/tt0106697/")
Movie.create(title:"Lucy", poster_img_url:"https://image.tmdb.org/t/p/w500/dhjyfcwEoW6jJ4Q7DpZTp6E58GA.jpg", imdb_page:"https://www.imdb.com/title/tt2872732/")
Movie.create(title:"I Origins", poster_img_url:"https://image.tmdb.org/t/p/w500/2P31jhd1dWUAPD8dmnSrwkQ8CNN.jpg", imdb_page:"https://www.imdb.com/title/tt2884206/")
Movie.create(title:"In Time", poster_img_url:"https://image.tmdb.org/t/p/w500/3Mwj2sIONQckOZP3YwsUXF7U5I4.jpg", imdb_page:"https://www.imdb.com/title/tt1637688/")
Movie.create(title:"Iron Man", poster_img_url:"https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg", imdb_page:"https://www.imdb.com/title/tt0371746/")
Movie.create(title:"Mad Max", poster_img_url:"https://image.tmdb.org/t/p/w500/5LrI4GiCSrChgkdskVZiwv643Kg.jpg", imdb_page:"https://www.imdb.com/title/tt0079501/")
Movie.create(title:"Hummingbird", poster_img_url:"https://image.tmdb.org/t/p/w500/bN2aGUOxHRwGms68WTDr2MHzkKa.jpg", imdb_page:"https://www.imdb.com/title/tt1893256/")
Movie.create(title:"Mr. Nobody", poster_img_url:"https://image.tmdb.org/t/p/w500/qNkIONc4Rgmzo23ph7qWp9QfVnW.jpg", imdb_page:"https://www.imdb.com/title/tt0485947/")
Movie.create(title:"The Great Gatsby", poster_img_url:"https://image.tmdb.org/t/p/w500/nimh1rrDDLhgpG8XAYoUZXHYwb6.jpg", imdb_page:"https://www.imdb.com/title/tt1343092/")
Movie.create(title:"Revolver", poster_img_url:"https://image.tmdb.org/t/p/w500/cXJYFEIGNxiNTCekP1A68ICzJen.jpg", imdb_page:"https://www.imdb.com/title/tt0365686/")
Movie.create(title:"Ponyo", poster_img_url:"https://image.tmdb.org/t/p/w500/yp8vEZflGynlEylxEesbYasc06i.jpg", imdb_page:"https://www.imdb.com/title/tt0876563/")
Movie.create(title:"Unbreakable", poster_img_url:"https://image.tmdb.org/t/p/w500/mLuehrGLiK5zFCyRmDDOH6gbfPf.jpg", imdb_page:"https://www.imdb.com/title/tt0217869/")
Movie.create(title:"Goodfellas", poster_img_url:"https://image.tmdb.org/t/p/w500/aKuFiU82s5ISJpGZp7YkIr3kCUd.jpg", imdb_page:"https://www.imdb.com/title/tt0099685/")
Movie.create(title:"Boyz N The Hood", poster_img_url:"https://image.tmdb.org/t/p/w500/v4ox4aSCNT5vyLXl4Q71JiWwCXW.jpg", imdb_page:"https://www.imdb.com/title/tt0101507/")
Movie.create(title:"Beetlejuice", poster_img_url:"https://image.tmdb.org/t/p/w500/nnl6OWkyPpuMm595hmAxNW3rZFn.jpg", imdb_page:"https://www.imdb.com/title/tt0094721/")
Movie.create(title:"The Holy Mountain", poster_img_url:"https://image.tmdb.org/t/p/w500/bvuWgH7MGYHBBdNeZcFDDA8vjYY.jpg", imdb_page:"https://www.imdb.com/title/tt0071615/")
Movie.create(title:"They Cloned Tyrone", poster_img_url:"https://image.tmdb.org/t/p/w500/hnzXoDaK346U4ByfvQenu2DZnTg.jpg", imdb_page:"https://www.imdb.com/title/tt9873892/")
Movie.create(title:"Wanted", poster_img_url:"https://image.tmdb.org/t/p/w500/cbDMsV4VJAL2xJ2JXdWWjmUXZkT.jpg", imdb_page:"https://www.imdb.com/title/tt0493464/")
Movie.create(title:"Rango", poster_img_url:"https://image.tmdb.org/t/p/w500/oVeRl1SRADz74OrY97usmP1flLV.jpg", imdb_page:"https://www.imdb.com/title/tt1192628/")
Movie.create(title:"Soul", poster_img_url:"https://image.tmdb.org/t/p/w500/hm58Jw4Lw8OIeECIq5qyPYhAeRJ.jpg", imdb_page:"https://www.imdb.com/title/tt2948372/")
Movie.create(title:"Cars", poster_img_url:"https://image.tmdb.org/t/p/w500/u4G8EkiIBZYx0wEg2xDlXZigTOZ.jpg", imdb_page:"https://www.imdb.com/title/tt0317219/")
Movie.create(title:"The Wolf of Wall Street", poster_img_url:"https://image.tmdb.org/t/p/w500/pWHf4khOloNVfCxscsXFj3jj6gP.jpg", imdb_page:"https://www.imdb.com/title/tt0993846/")
Movie.create(title:"Life of Pi", poster_img_url:"https://image.tmdb.org/t/p/w500/iLgRu4hhSr6V1uManX6ukDriiSc.jpg", imdb_page:"https://www.imdb.com/title/tt0454876/")
Movie.create(title:"Everything Everywhere All at Once", poster_img_url:"https://image.tmdb.org/t/p/w500/rKvCys0fMIIi1X9rmJBxTPLAtoU.jpg", imdb_page:"https://www.imdb.com/title/tt6710474/")
Movie.create(title:"Transformers: Dark of the Moon", poster_img_url:"https://image.tmdb.org/t/p/w500/28YlCLrFhONteYSs9hKjD1Km0Cj.jpg", imdb_page:"https://www.imdb.com/title/tt1399103/")
Movie.create(title:"The Matrix", poster_img_url:"https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg", imdb_page:"https://www.imdb.com/title/tt0133093/")
Movie.create(title:"The Silence of the Lambs", poster_img_url:"https://image.tmdb.org/t/p/w500/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg", imdb_page:"https://www.imdb.com/title/tt0102926/")
Movie.create(title:"The Dark Knight Rises", poster_img_url:"https://image.tmdb.org/t/p/w500/hr0L2aueqlP2BYUblTTjmtn0hw4.jpg", imdb_page:"https://www.imdb.com/title/tt1345836/")
Movie.create(title:"Enter the Void", poster_img_url:"https://image.tmdb.org/t/p/w500/krKnsfvSJM1PL40tLicRhVQ6kuG.jpg", imdb_page:"https://www.imdb.com/title/tt1191111/")
Movie.create(title:"50/50", poster_img_url:"https://image.tmdb.org/t/p/w500/8f9tM9JVB4ETBhxlQcXIjLckArl.jpg", imdb_page:"https://www.imdb.com/title/tt1306980/")
Movie.create(title:"About Time", poster_img_url:"https://image.tmdb.org/t/p/w500/iR1bVfURbN7r1C46WHFbwCkVve.jpg", imdb_page:"https://www.imdb.com/title/tt2194499/")
Movie.create(title:"The Secret Life of Walter Mitty", poster_img_url:"https://image.tmdb.org/t/p/w500/tY6ypjKOOtujhxiSwTmvA4OZ5IE.jpg", imdb_page:"https://www.imdb.com/title/tt0359950/")
Movie.create(title:"Birdman or (The Unexpected Virtue of Ignorance)", poster_img_url:"https://image.tmdb.org/t/p/w500/rHUg2AuIuLSIYMYFgavVwqt1jtc.jpg", imdb_page:"https://www.imdb.com/title/tt2562232/")
Movie.create(title:"Free Guy", poster_img_url:"https://image.tmdb.org/t/p/w500/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg", imdb_page:"https://www.imdb.com/title/tt6264654/")
Movie.create(title:"Ready Player One", poster_img_url:"https://image.tmdb.org/t/p/w500/pU1ULUq8D3iRxl1fdX2lZIzdHuI.jpg", imdb_page:"https://www.imdb.com/title/tt1677720/")
Movie.create(title:"The Usual Suspects", poster_img_url:"https://image.tmdb.org/t/p/w500/bUPmtQzrRhzqYySeiMpv7GurAfm.jpg", imdb_page:"https://www.imdb.com/title/tt0114814/")
Movie.create(title:"Peaceful Warrior", poster_img_url:"https://image.tmdb.org/t/p/w500/r4VQCZe3aSo7TmmsxcyLqaoMR1l.jpg", imdb_page:"https://www.imdb.com/title/tt0438315/")
Movie.create(title:"What Dreams May Come", poster_img_url:"https://image.tmdb.org/t/p/w500/2gUfJKfJ6LwdqQebiAWuNzIWyp9.jpg", imdb_page:"https://www.imdb.com/title/tt0120889/")
Movie.create(title:"Uncle Buck", poster_img_url:"https://image.tmdb.org/t/p/w500/i0MuRxuENc9Ur3croChw0Tmrs5G.jpg", imdb_page:"https://www.imdb.com/title/tt0098554/")
Movie.create(title:"The Wizard of Oz", poster_img_url:"https://image.tmdb.org/t/p/w500/bSA6DbAC5gdkaooU164lQUX6rVs.jpg", imdb_page:"https://www.imdb.com/title/tt0032138/")
Movie.create(title:"American Psycho", poster_img_url:"https://image.tmdb.org/t/p/w500/9uGHEgsiUXjCNq8wdq4r49YL8A1.jpg", imdb_page:"https://www.imdb.com/title/tt0144084/")
Movie.create(title:"Half Baked", poster_img_url:"https://image.tmdb.org/t/p/w500/14TmEac4bquNaEld9t0uIliYoKE.jpg", imdb_page:"https://www.imdb.com/title/tt0120693/")
Movie.create(title:"Slacker", poster_img_url:"https://image.tmdb.org/t/p/w500/uNtzrTiQQMHwabGr0aAi8TvuII9.jpg", imdb_page:"https://www.imdb.com/title/tt0102943/")
Movie.create(title:"Waking Life", poster_img_url:"https://image.tmdb.org/t/p/w500/2MRM4PL6H7yraAkwyUEe2EqoQH3.jpg", imdb_page:"https://www.imdb.com/title/tt0243017/")
Movie.create(title:"Joker", poster_img_url:"https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg", imdb_page:"https://www.imdb.com/title/tt7286456/")
Movie.create(title:"Into the Wild", poster_img_url:"https://image.tmdb.org/t/p/w500/2MSGZEE6XZd2r4ODNziwAw7Hpw0.jpg", imdb_page:"https://www.imdb.com/title/tt0758758/")
Movie.create(title:"Akira", poster_img_url:"https://image.tmdb.org/t/p/w500/neZ0ykEsPqxamsX6o5QNUFILQrz.jpg", imdb_page:"https://www.imdb.com/title/tt0094625/")
Movie.create(title:"Sympathy for the Devil", poster_img_url:"https://image.tmdb.org/t/p/w500/afGdVMa80LMs6ibLP22CwM5uI4e.jpg", imdb_page:"https://www.imdb.com/title/tt21991654/")
Movie.create(title:"Ghost in the Shell", poster_img_url:"https://image.tmdb.org/t/p/w500/9gC88zYUBARRSThcG93MvW14sqx.jpg", imdb_page:"https://www.imdb.com/title/tt0113568/")
Movie.create(title:"Source Code", poster_img_url:"https://image.tmdb.org/t/p/w500/AtQDTlj3MFOXJd5C9OopaRo3rRo.jpg", imdb_page:"https://www.imdb.com/title/tt0945513/")
